export type { IFile } from './IFile'
export type { ITheme } from "./ITheme";
export type { IColor } from "./ITheme/IColor";
export type { IFontSize } from "./ITheme/IFontSize";
export type { IFontWeight } from "./ITheme/IFontWeight";
export type { ISectionItem } from "./ISectionItem";
export type { ISection } from './ISection'
export type { IContent } from './IContent'
export type { IWidgetsList } from './IWidgetsList'
export type { IDefaultImage } from './IDefaultImage'
export type { IStyledSection } from './IStyledSection'