export {
    AlignHorizontalCenterIcon,
    FormatAlignRightIcon,
    FormatColorFillIcon,
    AlignVerticalTopIcon,
    FormatAlignCenterIcon,
    FormatAlignLeftIcon,
    ViewColumnRoundedIcon,
    TableRowsRoundedIcon,
    UploadFileIcon,
    FormatBoldRoundedIcon,
    FormatItalicRoundedIcon,
    ColorizeIcon,
    FileOpenOutlinedIcon,
    AddIcon,
    TextFieldsIcon,
    ImageIcon,
    DonutLargeSharpIcon,
    VerticalAlignCenter,
    AlignVerticalBottom,
} from '../icons'